platform: linux

image_resource:
  type: docker-image
  source:
    repository: 10.34.54.29:5000/java
    tag: "8"
    insecure_registries: ["10.34.54.29:5000"]
inputs:
  - name: version
  - name: repo
  - name: repo-master
outputs:
  - name: out
run:
  path: repo/concourse/tasks/bump-to-next-develop-version.sh