platform: linux

image_resource:
  type: docker-image
  source:
    repository: boyi/java

inputs:
- name: source-code

outputs:
- name: target-web

run:
  path: source-code/concourse/tasks/package-web.sh
