platform: linux

image_resource:
  type: docker-image
  source:
    repository: 10.34.54.29:5000/java
    tag: "8"
    insecure_registries: ["10.34.54.29:5000"]
inputs:
- name: source-code

run:
  path: source-code/concourse/tasks/unit-test-web.sh
